# Generated by Django 3.2.4 on 2021-06-17 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('name', models.CharField(db_index=True, max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('match_number', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('vs', models.CharField(max_length=255)),
                ('schedule', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('name', models.CharField(db_index=True, max_length=100, primary_key=True, serialize=False)),
                ('dateOfBirth', models.DateField(null=True)),
                ('odiCenturies', models.IntegerField(null=True)),
                ('testCenturies', models.IntegerField(null=True)),
                ('t20Centuries', models.IntegerField(null=True)),
                ('noOfAwards', models.IntegerField(null=True)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('rank', models.IntegerField(primary_key=True, serialize=False)),
                ('totalWon', models.IntegerField()),
                ('totalLost', models.IntegerField()),
                ('teamName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('name', models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False)),
                ('captain', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('name', models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winningTeam', models.CharField(max_length=100)),
                ('loosingTeam', models.CharField(max_length=100)),
                ('matchNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cricket.matches')),
            ],
        ),
        migrations.CreateModel(
            name='MatchSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1', models.CharField(max_length=100)),
                ('team2', models.CharField(max_length=100)),
                ('winner', models.CharField(max_length=100)),
                ('looser', models.CharField(max_length=100)),
                ('manOfTheMatch', models.CharField(max_length=100)),
                ('bowlerOfTheMatch', models.CharField(max_length=100)),
                ('bestFielder', models.CharField(max_length=100)),
                ('match_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cricket.matches', unique=True)),
            ],
        ),
    ]
